name: AQI 72h - Predict for Time

on:
  workflow_dispatch:
    inputs:
      target_time:
        description: "Target time in ISO 8601. Examples: 2026-01-25T15:00:00Z OR 2026-01-25T15:00:00+05:00"
        required: true
        default: "2026-01-25T15:00:00Z"

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: rf_pm25_next72h_model
          path: models

      - name: Predict for requested time
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          TARGET_TIME_UTC: ${{ inputs.target_time }}
        run: |
          ls -la models
          python 05_predict_pm25_for_time_next72h.py
